#!/bin/sh
#exec ./terrainmaker --threads 0 -ofoo.pnm -W1920 -H1080 -s scripts/world.tm
exec ./terrainmaker --threads 0 -ofoo.pnm -W480 -H256 -s scripts/world.tm
#exec ./terrainmaker --threads 0 -ofoo.pnm -W800 -H480 -s scripts/world.tm

